import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Brain, CheckCircle2, ClipboardList, FileText, FlaskConical, GraduationCap, Layers, Library, ListChecks, Search, ShieldCheck, Timer, Trophy } from 'lucide-react';
import './styles/main.css';
import blueprint from './data/examBlueprint.json';
import lessons from './data/lessons.json';
import quizzes from './data/quizzes.json';
import labs from './data/labs.json';
import mockExams from './data/mockExams.json';
import flashcards from './data/flashcards.json';
import glossary from './data/glossary.json';
import sources from './data/sources.json';
import coverageMatrix from './data/coverageMatrix.json';
import scenarios from './data/scenarios.json';
import studyPlans from './data/studyPlans.json';
import cramGuide from './data/cramGuide.json';
import readinessData from './data/readiness.json';
import uiWalkthroughs from './data/uiWalkthroughs.json';

const DATA = { blueprint, lessons, quizzes, labs, mockExams, flashcards, glossary, sources, coverageMatrix, scenarios, studyPlans, cramGuide, readinessData, uiWalkthroughs };
const navItems = [
  ['home','Home',Trophy], ['blueprint','Blueprint',Layers], ['domains','Domains',BookOpen], ['lessons','Lessons',FileText], ['walkthroughs','Walkthroughs',Search], ['labs','Labs',FlaskConical], ['quiz','Quiz',ClipboardList], ['mock','Mock exam',Timer], ['flashcards','Flashcards',Brain], ['glossary','Glossary',Library], ['readiness','Readiness',ShieldCheck], ['study-plan','Study plan',ListChecks], ['cram','Cram guide',GraduationCap]
];
function useHashRoute(){
  const parse=()=>{const raw=location.hash.replace(/^#/,'')||'home'; const [page,id]=raw.split('/'); return {page,id};};
  const [route,setRoute]=useState(parse);
  useEffect(()=>{const on=()=>setRoute(parse()); addEventListener('hashchange',on); return()=>removeEventListener('hashchange',on);},[]);
  return route;
}
function useProgress(){
  const [progress,setProgress]=useState(()=>JSON.parse(localStorage.getItem('gh600-progress-v2')||'{"lessons":{},"flashcards":{},"quizScores":{},"mockScores":{}}'));
  const save=(next)=>{setProgress(next); localStorage.setItem('gh600-progress-v2',JSON.stringify(next));};
  return [progress,save];
}
function pct(done,total){return total?Math.round((done/total)*100):0}
function byId(list,id){return list.find(x=>x.id===id)}
function sourceNames(ids){return ids.map(id=>byId(sources,id)).filter(Boolean)}
function Layout({children,progress}){
 const done=Object.values(progress.lessons||{}).filter(Boolean).length;
 return <><header className="topbar"><a className="brand" href="#home"><span>GH</span><strong>GH-600 Study Platform</strong></a><nav aria-label="Primary navigation">{navItems.map(([id,label,Icon])=><a key={id} href={'#'+id}><Icon size={16} aria-hidden="true" />{label}</a>)}</nav></header><main id="main" className="shell">{children}</main><footer><p>Unofficial GH-600 study resource. Always verify current exam objectives with Microsoft Learn before sitting the exam.</p><p>{done}/{lessons.length} lessons marked studied ({pct(done,lessons.length)}%).</p></footer></>;
}
function Stat({label,value,icon:Icon}){return <div className="stat"><Icon aria-hidden="true"/><strong>{value}</strong><span>{label}</span></div>}
function ProgressBar({value,label}){return <div className="progress"><div><span>{label}</span><strong>{value}%</strong></div><meter min="0" max="100" value={value}>{value}%</meter></div>}
function SourcePanel({ids}){const list=sourceNames(ids); return <aside className="source-panel"><h3>Related sources</h3>{list.map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer"><strong>{s.title}</strong><span>{s.publisher}</span></a>)}</aside>}
function Home({progress}){
 const studied=Object.values(progress.lessons||{}).filter(Boolean).length;
 const next=lessons.find(l=>!progress.lessons?.[l.id])||lessons[0];
 const domainStats=blueprint.domains.map(d=>{const dl=lessons.filter(l=>l.domainId===d.id); return {...d, percent:pct(dl.filter(l=>progress.lessons?.[l.id]).length,dl.length)}});
 return <section><div className="hero"><div><p className="eyebrow">Microsoft/GitHub certification prep</p><h1>GH-600: Developing in Agentic AI Systems</h1><p>A source-grounded study platform for agentic SDLC workflows, Copilot cloud agent, MCP, GitHub controls, evaluation, multi-agent coordination, guardrails, and accountability.</p><div className="actions"><a className="button primary" href={'#lesson/'+next.id}>Start next lesson</a><a className="button" href="#blueprint">Review blueprint</a><a className="button" href="#mock">Take mock exam</a></div></div><div className="panel"><h2>Recommended next</h2><p>{next.title}</p><p className="muted">{next.domain}</p><ProgressBar label="Total progress" value={pct(studied,lessons.length)} /></div></div><div className="stats"><Stat icon={FileText} label="Lessons" value={lessons.length}/><Stat icon={ClipboardList} label="Quiz questions" value={quizzes.length}/><Stat icon={Timer} label="Mock exams" value={mockExams.length}/><Stat icon={Brain} label="Flashcards" value={flashcards.length}/><Stat icon={FlaskConical} label="Labs" value={labs.length}/><Stat icon={Search} label="UI walkthroughs" value={uiWalkthroughs.length}/><Stat icon={CheckCircle2} label="Official skills mapped" value={coverageMatrix.length}/></div><section className="grid two"><div className="panel"><h2>Domain readiness</h2>{domainStats.map(d=><ProgressBar key={d.id} label={d.title+' '+d.weight} value={d.percent}/>)}</div><div className="panel"><h2>Quick path</h2><ol className="steps"><li>Open the blueprint and inspect every skill.</li><li>Study domain lessons in order.</li><li>Complete at least one lab in each domain.</li><li>Use UI walkthroughs to rehearse GitHub control-plane flows.</li><li>Use quizzes for weak-area feedback.</li><li>Finish with mock exams and the cram guide.</li></ol></div></section></section>
}
function Blueprint(){return <section><PageTitle eyebrow="Exam blueprint" title="Official skill coverage map" text="Every official GH-600 skill is mapped to lessons, quiz questions, labs, flashcards, and sources."/><div className="domain-strip">{blueprint.domains.map(d=><a href={'#domain/'+d.id} className="domain-card" key={d.id}><span>{d.weight}</span><strong>{d.title}</strong><p>{d.whatExamTests}</p></a>)}</div><div className="table-wrap"><table><thead><tr><th>Skill</th><th>Domain</th><th>Lesson</th><th>Quiz</th><th>Lab</th><th>Status</th></tr></thead><tbody>{coverageMatrix.map(r=><tr key={r.id}><td>{r.skill}</td><td>{r.domain}</td><td>{r.lessonIds.map(id=><a key={id} href={'#lesson/'+id}>{id}</a>)}</td><td>{r.quizQuestionIds.length}</td><td>{r.labIds.join(', ')}</td><td><span className="badge good">{r.coverageStatus}</span></td></tr>)}</tbody></table></div></section>}
function Domains({progress}){return <section><PageTitle eyebrow="Domains" title="Study by exam domain" text="Each domain includes grouped lessons, traps, labs, and completion status."/><div className="domain-grid">{blueprint.domains.map(d=><DomainCard key={d.id} domain={d} progress={progress}/>)}</div></section>}
function DomainCard({domain,progress}){const dl=lessons.filter(l=>l.domainId===domain.id); const done=dl.filter(l=>progress.lessons?.[l.id]).length; return <article className="domain-card"><span>{domain.weight}</span><h2>{domain.title}</h2><p>{domain.whatExamTests}</p><ProgressBar label="Lessons studied" value={pct(done,dl.length)}/><a className="button" href={'#domain/'+domain.id}>Open domain</a></article>}
function DomainPage({id,progress,setProgress}){const d=blueprint.domains.find(x=>x.id===id)||blueprint.domains[0]; const dl=lessons.filter(l=>l.domainId===d.id); return <section><PageTitle eyebrow={d.weight} title={d.title} text={d.whatExamTests}/><div className="grid two"><div className="panel"><h2>What the exam is really testing</h2><p>{d.whatExamTests}</p><h3>Recommended study order</h3><ol>{d.groups.map(g=><li key={g.id}>{g.title}</li>)}</ol></div><div className="panel"><h2>Key exam traps</h2><ul><li>Giving agents broad tools without a task-specific need.</li><li>Accepting claims without logs, checks, artifacts, or review evidence.</li><li>Skipping human approval for sensitive, irreversible, production, or compliance-relevant work.</li><li>Using many agents without isolation and handoff contracts.</li></ul></div></div>{d.groups.map(g=><section key={g.id} className="panel"><h2>{g.title}</h2><div className="lesson-list">{dl.filter(l=>l.group===g.title).map(l=><LessonRow key={l.id} lesson={l} progress={progress} setProgress={setProgress}/>)}</div></section>)}<section className="panel"><h2>Additional practical knowledge</h2><div className="lesson-list">{dl.filter(l=>l.extended).map(l=><LessonRow key={l.id} lesson={l} progress={progress} setProgress={setProgress}/>)}</div></section></section>}
function LessonRow({lesson,progress,setProgress}){const checked=!!progress.lessons?.[lesson.id]; return <article className="lesson-row"><input aria-label={'Mark '+lesson.title+' studied'} type="checkbox" checked={checked} onChange={e=>setProgress({...progress,lessons:{...progress.lessons,[lesson.id]:e.target.checked}})}/><div><a href={'#lesson/'+lesson.id}><strong>{lesson.title}</strong></a><p>{lesson.whyExam}</p></div><span className="badge">{lesson.difficulty}</span></article>}
function Lessons({progress,setProgress}){const [q,setQ]=useState(''); const filtered=lessons.filter(l=>(l.title+l.domain+l.group).toLowerCase().includes(q.toLowerCase())); return <section><PageTitle eyebrow="Lessons" title="Complete course library" text="Search and open any lesson. Each lesson includes exam mapping, GitHub implementation detail, scenarios, traps, takeaways, revision questions, and sources."/><label className="search"><Search aria-hidden="true"/><span className="sr-only">Search lessons</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search lessons, domains, skills"/></label><div className="lesson-list">{filtered.map(l=><LessonRow key={l.id} lesson={l} progress={progress} setProgress={setProgress}/>)}</div></section>}
function Lesson({id,progress,setProgress}){const l=byId(lessons,id)||lessons[0]; const relatedQ=quizzes.filter(q=>q.lessonId===l.id).slice(0,5); const relatedLab=labs.find(lab=>lab.skillIds.includes(l.skillId)); const sc=scenarios.find(s=>s.lessonId===l.id); return <section><PageTitle eyebrow={l.domain} title={l.title} text={l.whyExam}/><div className="grid lesson-layout"><article className="panel lesson"><button className="button small" onClick={()=>setProgress({...progress,lessons:{...progress.lessons,[l.id]:!progress.lessons?.[l.id]}})}>{progress.lessons?.[l.id]?'Mark not studied':'Mark studied'}</button><h2>Official exam skill mapping</h2><p>{l.officialSkill}</p><h2>Core explanation</h2>{l.core.map((p,i)=><p key={i}>{p}</p>)}<h2>GitHub-specific implementation detail</h2><p>{l.githubDetail}</p><h2>Practical example</h2><p>{l.practicalExample}</p>{l.caseStudy&&<CaseStudy study={l.caseStudy}/>}<ScenarioCard scenario={sc||l.scenario}/><h2>Common exam trap</h2><p>{l.examTrap}</p><h2>Key takeaways</h2><ul>{l.takeaways.map(t=><li key={t}>{t}</li>)}</ul><h2>Revision questions</h2><ol>{l.revisionQuestions.map(r=><li key={r}>{r}</li>)}</ol><h2>Related quiz questions</h2>{relatedQ.map(q=><p key={q.id}><a href={'#quiz/'+q.id}>{q.question}</a></p>)}{relatedLab&&<p><a className="button" href={'#labs/'+relatedLab.id}>Open related lab</a></p>}</article><SourcePanel ids={l.sourceIds}/></div></section>}
function CaseStudy({study}){return <section className="case-study"><h2>{study.title}</h2><dl><div><dt>Repository</dt><dd>{study.repository}</dd></div><div><dt>Issue</dt><dd>{study.issue}</dd></div><div><dt>Situation</dt><dd>{study.situation}</dd></div><div><dt>Decision</dt><dd>{study.decision}</dd></div><div><dt>Wrong move</dt><dd>{study.wrongMove}</dd></div><div><dt>Review artifact</dt><dd>{study.reviewArtifact}</dd></div><div><dt>Reviewer question</dt><dd>{study.reviewerQuestion}</dd></div></dl></section>}
function ScenarioCard({scenario}){return <aside className="scenario-card"><h3>{scenario.title}</h3><p>{scenario.body||scenario.prompt}</p>{scenario.goodAnswer&&<p><strong>Strong answer:</strong> {scenario.goodAnswer}</p>}</aside>}

function Walkthroughs({id}){const selected=id&&byId(uiWalkthroughs,id); const list=selected?[selected]:uiWalkthroughs; return <section><PageTitle eyebrow="GitHub control-plane practice" title="UI workflow walkthroughs" text="Original schematic walkthroughs for the GitHub flows GH-600 expects you to understand. These are not copied screenshots; they are accessible study diagrams and verification checklists."/><div className="cards">{list.map(w=><WalkthroughCard key={w.id} item={w}/>)}</div></section>}
function WalkthroughCard({item}){return <article className="card walkthrough"><span className="badge">{item.domainIds.join(', ')}</span><h2>{item.title}</h2><div className="mock-screen" role="img" aria-label={'Schematic GitHub screen for '+item.title}><div className="mock-top"><span></span><span></span><span></span><strong>{item.screen.area}</strong></div><div className="mock-body"><h3>{item.screen.primary}</h3><p>{item.screen.secondary}</p><div className="mock-badges">{item.screen.badges.map(b=><span key={b}>{b}</span>)}</div></div></div><h3>Steps</h3><ol>{item.steps.map(s=><li key={s}>{s}</li>)}</ol><h3>What to verify</h3><ul>{item.verify.map(v=><li key={v}>{v}</li>)}</ul><p><strong>Exam trap:</strong> {item.examTrap}</p><SourceLinks ids={item.sourceIds}/></article>}

function Labs({id}){const selected=id&&byId(labs,id); const list=selected?[selected]:labs; return <section><PageTitle eyebrow="Hands-on" title="Practical labs" text="Labs turn GH-600 knowledge into GitHub artifacts, validation evidence, and recovery habits."/><div className="cards">{list.map(l=><LabCard key={l.id} lab={l}/>)}</div></section>}
function LabCard({lab}){return <article className="card"><span className="badge">{lab.domain}</span><h2>{lab.title}</h2><p><strong>Objective:</strong> {lab.objective}</p><h3>Required tools</h3><ul>{lab.requiredTools.map(x=><li key={x}>{x}</li>)}</ul><h3>Steps</h3><ol>{lab.steps.map(x=><li key={x}>{x}</li>)}</ol><p><strong>Expected result:</strong> {lab.expectedResult}</p><p><strong>Validation:</strong> {lab.validation}</p><p><strong>Common failure:</strong> {lab.commonFailure}</p><p><strong>Recovery:</strong> {lab.recovery}</p><p><strong>Exam relevance:</strong> {lab.examRelevance}</p><SourceLinks ids={lab.sourceIds}/></article>}
function SourceLinks({ids}){return <p className="sources-inline">Sources: {sourceNames(ids).map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}</a>)}</p>}
function Quiz({id,progress,setProgress}){const [domain,setDomain]=useState('all'); const [answers,setAnswers]=useState({}); const pool=(id?[byId(quizzes,id)].filter(Boolean):quizzes.filter(q=>domain==='all'||q.domainId===domain).slice(0,30)); const score=Object.entries(answers).filter(([qid,a])=>pool.find(q=>q.id===qid)?.correctIndex===a).length; return <section><PageTitle eyebrow="Practice" title="Quiz engine" text="Immediate feedback, wrong-answer rationale, domain tags, skill tags, and weak-area review."/><label>Filter by domain <select value={domain} onChange={e=>{setDomain(e.target.value); setAnswers({});}}><option value="all">All domains</option>{blueprint.domains.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><div aria-live="polite" className="score">Score: {score}/{Object.keys(answers).length || pool.length}</div>{pool.map(q=><QuizQuestion key={q.id} q={q} answer={answers[q.id]} onAnswer={a=>setAnswers({...answers,[q.id]:a})}/>)}</section>}
function QuizQuestion({q,answer,onAnswer}){return <article className="question"><p className="eyebrow">{q.domain} · {q.difficulty}</p><h2>{q.question}</h2>{q.options.map((o,i)=><button key={o} className={'option '+(answer!==undefined?(i===q.correctIndex?'correct':i===answer?'wrong':''):'')} onClick={()=>onAnswer(i)} disabled={answer!==undefined}>{o}</button>)}{answer!==undefined&&<div className="feedback" role="status"><p>{answer===q.correctIndex?'Correct.':'Not quite.'} {q.correctExplanation}</p>{q.wrongRationales.map(w=><p key={w.optionIndex}><strong>Option {w.optionIndex+1}:</strong> {w.rationale}</p>)}<SourceLinks ids={q.sourceIds}/></div>}</article>}
function MockExam({progress,setProgress}){const [examId,setExamId]=useState(mockExams[0].id); const [review,setReview]=useState(false); const [answers,setAnswers]=useState({}); const exam=byId(mockExams,examId); const qs=exam.questionIds.map(id=>byId(quizzes,id)).filter(Boolean); const score=qs.filter(q=>answers[q.id]===q.correctIndex).length; const byDomain=blueprint.domains.map(d=>{const dqs=qs.filter(q=>q.domainId===d.id); return {domain:d.title,score:dqs.filter(q=>answers[q.id]===q.correctIndex).length,total:dqs.length};}); return <section><PageTitle eyebrow="Mock exam" title="Timed and review practice" text="Three full practice exams with domain feedback. Use review mode to study explanations."/><div className="toolbar"><label>Exam <select value={examId} onChange={e=>{setExamId(e.target.value);setAnswers({});}}>{mockExams.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><button className="button" onClick={()=>setReview(!review)}>{review?'Hide review':'Review mode'}</button><button className="button primary" onClick={()=>setProgress({...progress,mockScores:{...progress.mockScores,[examId]:pct(score,qs.length)}})}>Save score</button></div><div className="score"><strong>{score}/{qs.length}</strong> · {pct(score,qs.length)}% · {exam.durationMinutes} minutes recommended</div><div className="cards small-cards">{byDomain.map(d=><div className="mini" key={d.domain}>{d.domain}<strong>{d.total?pct(d.score,d.total):0}%</strong></div>)}</div>{qs.map(q=><QuizQuestion key={q.id} q={q} answer={answers[q.id]} onAnswer={a=>setAnswers({...answers,[q.id]:a})}/>)}</section>}
function Flashcards({progress,setProgress}){const [q,setQ]=useState(''); const [flipped,setFlipped]=useState({}); const cards=flashcards.filter(c=>(c.front+c.back).toLowerCase().includes(q.toLowerCase())).slice(0,80); return <section><PageTitle eyebrow="Recall" title="Flashcards" text="Search, flip, and mark cards as known or needs review. Progress is saved locally."/><label className="search"><Search aria-hidden="true"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search flashcards"/></label><div className="flash-grid">{cards.map(c=><article className="flash" key={c.id}><button onClick={()=>setFlipped({...flipped,[c.id]:!flipped[c.id]})}><span>{c.domainId}</span><strong>{flipped[c.id]?c.back:c.front}</strong></button><div className="actions"><button onClick={()=>setProgress({...progress,flashcards:{...progress.flashcards,[c.id]:'known'}})}>Known</button><button onClick={()=>setProgress({...progress,flashcards:{...progress.flashcards,[c.id]:'review'}})}>Needs review</button></div></article>)}</div></section>}
function Glossary(){const [q,setQ]=useState(''); const terms=glossary.filter(g=>(g.term+g.definition).toLowerCase().includes(q.toLowerCase())); return <section><PageTitle eyebrow="Reference" title="Glossary" text="Search GitHub, AI-agent, governance, MCP, and SDLC terms."/><label className="search"><Search aria-hidden="true"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search glossary"/></label><div className="cards">{terms.map(g=><article className="card" key={g.id}><h2>{g.term}</h2><p>{g.definition}</p>{g.relatedLessons.map(id=><a key={id} href={'#lesson/'+id}>{byId(lessons,id)?.title}</a>)}</article>)}</div></section>}
function Readiness({progress}){const studied=pct(Object.values(progress.lessons||{}).filter(Boolean).length,lessons.length); const mockBest=Math.max(0,...Object.values(progress.mockScores||{})); const labReady=studied>80; const ready=studied>=90&&mockBest>=80; return <section><PageTitle eyebrow="Readiness" title={ready?'Ready evidence looks strong':'Not ready yet'} text="Readiness is based on studied skills, mock score, quiz practice, and completed labs. This page does not pretend readiness without evidence."/><div className="grid two"><div className="panel"><h2>Evidence</h2><ProgressBar label="Lessons studied" value={studied}/><ProgressBar label="Best mock exam" value={mockBest}/><ProgressBar label="Coverage matrix" value={100}/></div><div className="panel"><h2>Checklist</h2>{readinessData.criteria.map(c=><label className="check" key={c}><input type="checkbox" readOnly checked={c.includes('coverage')|| (c.includes('mock')&&mockBest>=80) || (c.includes('lab')&&labReady) || (c.includes('studied')&&studied>=90)}/>{c}</label>)}</div></div><div className="panel"><h2>Final revision plan</h2><ol><li>Complete unstuck lessons in the lowest-progress domain.</li><li>Retake quizzes for questions answered incorrectly.</li><li>Complete one lab from each domain.</li><li>Score 80%+ on at least one mock exam with no domain below 70%.</li><li>Read the cram guide the day before the exam.</li><li>Run the currentness review against the official Microsoft study guide before booking.</li><li>Use the walkthroughs page to rehearse issue assignment, PR review, Actions evidence, branch protection, rulesets, CODEOWNERS, environments, MCP, and session logs.</li></ol></div></section>}
function StudyPlan(){return <section><PageTitle eyebrow="Plan" title="Study schedules" text="Choose the pace that matches your deadline."/>{Object.entries(studyPlans).map(([name,items])=><div className="panel" key={name}><h2>{name.replace(/([A-Z])/g,' $1')}</h2><ol>{items.map(i=><li key={i}>{i}</li>)}</ol></div>)}</section>}
function CramGuide(){return <section><PageTitle eyebrow="Final review" title="Cram guide" text="High-yield decision rules, traps, definitions, and cheat sheets."/><div className="panel"><h2>High-yield topics</h2><ul>{cramGuide.highYield.map(x=><li key={x}>{x}</li>)}</ul></div>{cramGuide.decisionTables.map(t=><div className="table-wrap" key={t.title}><h2>{t.title}</h2><table><tbody>{t.rows.map((r,i)=><tr key={i}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div>)}<div className="panel"><h2>Cheat sheets</h2>{cramGuide.cheatsheets.map(x=><p key={x}>{x}</p>)}</div><div className="panel"><h2>Currentness check</h2><p>Before exam day, compare the official Microsoft GH-600 study guide with the coverage matrix. Update any changed skill, source, quiz, lab, or flashcard before trusting the readiness result.</p><p><a href="https://learn.microsoft.com/en-gb/credentials/certifications/resources/study-guides/gh-600" target="_blank" rel="noreferrer">Open official GH-600 study guide</a></p></div></section>}
function PageTitle({eyebrow,title,text}){return <div className="page-title"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text&&<p>{text}</p>}</div>}
function App(){const route=useHashRoute(); const [progress,setProgress]=useProgress(); useEffect(()=>{document.title='GH-600 · '+route.page;},[route]); let page; if(route.page==='blueprint') page=<Blueprint/>; else if(route.page==='domains') page=<Domains progress={progress}/>; else if(route.page==='domain') page=<DomainPage id={route.id} progress={progress} setProgress={setProgress}/>; else if(route.page==='lessons') page=<Lessons progress={progress} setProgress={setProgress}/>; else if(route.page==='lesson') page=<Lesson id={route.id} progress={progress} setProgress={setProgress}/>; else if(route.page==='walkthroughs') page=<Walkthroughs id={route.id}/>; else if(route.page==='labs') page=<Labs id={route.id}/>; else if(route.page==='quiz') page=<Quiz id={route.id} progress={progress} setProgress={setProgress}/>; else if(route.page==='mock') page=<MockExam progress={progress} setProgress={setProgress}/>; else if(route.page==='flashcards') page=<Flashcards progress={progress} setProgress={setProgress}/>; else if(route.page==='glossary') page=<Glossary/>; else if(route.page==='readiness') page=<Readiness progress={progress}/>; else if(route.page==='study-plan') page=<StudyPlan/>; else if(route.page==='cram') page=<CramGuide/>; else page=<Home progress={progress}/>; return <Layout progress={progress}>{page}</Layout>}

createRoot(document.getElementById('root')).render(<App />);
